version: "3.7"
services:

  postgres:
    image: postgres:12.0-alpine
    container_name: db-sm
    ports:
      - "5435:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "db-sm"
      POSTGRES_USER: "user"
      POSTGRES_PASSWORD: "password"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
volumes:
  postgres_data: