spring:
  liquibase:
    contexts: ${spring.profiles.active:}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5435/db-sm
    username: user
    password: password
