CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY NOT NULL,
  name VARCHAR NOT NULL,
  email VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS posts (
  id SERIAL PRIMARY KEY NOT NULL,
  title VARCHAR NOT NULL,
  text VARCHAR NOT NULL,
  image_url VARCHAR,
  create_time TIMESTAMP
);

CREATE TABLE IF NOT EXISTS subscribers (
  id SERIAL PRIMARY KEY NOT NULL,
  first_id INT NOT NULL REFERENCES users(id),
  second_id INT NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS friends (
  id SERIAL PRIMARY KEY NOT NULL,
  first_id INT NOT NULL REFERENCES users(id),
  second_id INT NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS chat_messages (
  id SERIAL PRIMARY KEY NOT NULL,
  text TEXT NOT NULL,
  send_time TIMESTAMP NOT NULL,
  first_id INT NOT NULL REFERENCES users(id),
  second_id INT NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS activity (
  id SERIAL PRIMARY KEY NOT NULL,
  user_id INT NOT NULL REFERENCES users(id),
  post_id INT NOT NULL REFERENCES posts(id),
  create_time TIMESTAMP
);
